name: Tools
version: '${project.version}'
main: gamesmc.tools.Tools
api-version: 1.18
author: ReferTV
description: "Tools plugin"
softdepend: [PlaceholderAPI]

default-permission: gamesmc.patron

commands:
  crafting:
    aliases: [craft, workbench]
  ender:
    aliases: [enderchest]
  anvil:
    aliases: [al, kowadlo]
  loom:
    aliases: [lm]
  grindstone:
    aliases: [gs]
  stonecutter:
    aliases: [sc]
  smithingtable:
  gridstone:
  cartography:
    aliases: [ct, cartographytable]
  smitching:
    aliases: [st, smitchingtable]
  invsee:
    aliases: [inv, inventory]
  tools:
  vanish:
  online:
  gamemode:
    usage: /gamemode <0/1/2/3>
    aliases: [gm]
  setslots:
  heal:
  head:
  fly:
  feed:
  time:
  item:
  playerinfo:
  speed: